"""Utility functions for running the main server loop in flwr next."""

from collections.abc import Callable, Generator
from dataclasses import asdict
from logging import DEBUG
import time
from flwr.common import (
    Parameters,
    log,
    Message,
    DEFAULT_TTL,
    RecordSet,
    FitIns,
    ConfigsRecord,
    EvaluateIns,
)
from flwr.common.recordset_compat import fitins_to_recordset, evaluateins_to_recordset
from flwr.common.typing import ConfigsRecordValues
from flwr.server import Driver

from flower_llm.utils import ClientState


class TooManyFailuresError(Exception):
    """Exception raised when a client is dropped out of the tree."""


def wait_for_nodes_to_connect(driver: Driver, n_nodes: int, timeout: float = 3) -> None:
    """Wait for a specified number of client nodes to connect.

    This function continuously checks the number of client nodes that have connected by
    calling the `get_node_ids` method on the provided driver object. It logs the current
    number of connected client nodes at each check. The function will exit once the
    number of connected client nodes meets or exceeds the specified `n_nodes`. If the
    required number of nodes are not found, the function will wait for the specified
    `timeout` period before checking again.

    Parameters
    ----------
    driver : Driver
        The driver object used to interact with the client nodes.
    n_nodes : int
        The minimum number of client nodes that must be connected.
    timeout : float, optional
        The time in seconds to wait between checks. Default is 3 seconds.

    Returns
    -------
    None
    """
    # The Driver API might not immediately return enough client node IDs, so we
    # loop and wait until enough client nodes are available.
    while True:
        all_node_ids = driver.get_node_ids()
        log(DEBUG, f"Got {len(all_node_ids)} client nodes: {all_node_ids}")
        if len(all_node_ids) >= n_nodes:
            break
        time.sleep(timeout)


def message_collaborative(
    driver: Driver,
    message_type: str,
    sampled_clients: list[int] | list[str],
    gen_ins_function: Callable[[int, int | str], dict[str, ConfigsRecordValues]],
    all_node_ids: list[int],
    current_round: int,
    client_state: dict[str | int, ClientState],
    server_steps_cumulative: int,
    msg_str: str,
) -> Generator[Message, None, None]:
    """Generate and send collaborative messages to the nodes and handles the responses.

    This function is designed for federated learning scenarios where a server needs to
    communicate with a subset of clients for training or evaluation purposes. It
    generates messages based on the provided message type and instructions, sends them
    to the sampled clients, and yields the responses received. The function supports
    dynamic message generation based on the current round of communication and the
    specific needs of each client.

    Parameters
    ----------
    driver : Driver
        The communication driver used for message creation, sending, and receiving.
    message_type : str
        The type of message to be sent (e.g., "fit", "evaluate").
    sampled_clients : list[int] | list[str]
        A list of client identifiers (either integers or strings) that have been sampled
        for participation in the current round.
    gen_ins_function : Callable[[int, int | str], dict[str, ConfigsRecordValues]]
        A function that generates instruction configurations for each client based on
        the current round and the client's identifier.
    all_node_ids : list[int]
        A list of all node identifiers in the network.
    current_round : int
        The current round of the federated learning process.
    client_state : dict[str | int, ClientState]
        A dictionary mapping client identifiers to their current state.
    server_steps_cumulative : int
        The cumulative number of steps completed by the server.
    msg_str : str
        A string identifier used to prefix keys in the message's content and to locate
        specific parameters within the recordset.

    Yields
    ------
    Generator[Message, None, None]
        A generator that yields responses received from the clients as Message objects.

    Notes
    -----
    - The function constructs separate record sets for each client based on the
        instructions generated by `gen_ins_function` and updates these with
        configuration records.
    - It then creates messages for all nodes in `all_node_ids` using these record sets
        and sends them using the driver. The function handles the responses, sending
        additional messages if necessary, and yields the responses received.
    - This function is part of a larger federated learning framework and assumes the
        existence of `Driver`, `Message`, `RecordSet`, `ConfigsRecord`, and
        `ClientState` classes or interfaces.
    """
    log(DEBUG, "Collaborative messaging.")
    # Constructing separate record sets for each client
    record_sets: list[RecordSet] = []
    for cid in sampled_clients:
        record_set = fit_or_evaluate_ins_recordset(
            msg_str, current_round, [cid], client_state, server_steps_cumulative  # type: ignore[reportArgumentType, arg-type]
        )
        # Create a config record for the client
        record_set.configs_records.update(
            {str(cid): ConfigsRecord(gen_ins_function(current_round, cid))}
        )
        record_sets.append(record_set)

    messages: list[Message] = []
    for node_id in all_node_ids:
        if not record_sets:
            break
        message = driver.create_message(
            content=record_sets.pop(),
            message_type=message_type,
            dst_node_id=node_id,
            group_id=str(current_round),
            ttl=DEFAULT_TTL,
        )
        messages.append(message)
    message_ids = driver.push_messages(messages)
    received = 0
    total = len(record_sets)
    log(DEBUG, "Pushed %s messages: %s", len(messages), message_ids)

    while received < total:
        replies = list(driver.pull_messages(message_ids=message_ids))
        messages = []
        for res in replies:
            log(DEBUG, f"Got 1 {'result' if res.has_content() else 'error'}")
            received += 1
            node_id = res.metadata.src_node_id
            if record_sets:
                message = driver.create_message(
                    content=record_sets.pop(),
                    message_type=message_type,
                    dst_node_id=node_id,
                    group_id=str(current_round),
                    ttl=DEFAULT_TTL,
                )
                messages.append(message)
        if messages:
            message_ids = driver.push_messages(messages)
            log(DEBUG, "Pushed another %s messages: %s", len(messages), message_ids)
        for res in replies:
            yield res


def message_independent(
    driver: Driver,
    message_type: str,
    gen_ins_function: Callable[[int, int | str], dict[str, ConfigsRecordValues]],
    all_node_ids: list[int],
    current_round: int,
    assignment_function: Callable[[int], list[int] | list[str]],
    client_state: dict[str | int, ClientState],
    server_steps_cumulative: int,
    msg_str: str,
) -> Generator[Message, None, None]:
    """Generate and send messages to nodes for independent processing and yield results.

    This function is designed to operate in a federated learning context where messages
    containing instructions or data are sent to various nodes (clients or servers) for
    processing. It first assigns clients to nodes based on the `assignment_function`,
    then generates messages for each node using the `gen_ins_function` to create the
    content. These messages are sent out via the `driver`, and the function then waits
    for and yields the results as they arrive.

    Parameters
    ----------
    driver : Driver
        The communication driver responsible for message creation, sending, and
        receiving.
    message_type : str
        The type of the message to be sent, defining its purpose or action to be taken
        by the receiver.
    gen_ins_function : Callable[[int, int | str], dict[str, ConfigsRecordValues]]
        A function that generates the instruction set for a message given the current
        round and a client identifier. It returns a dictionary of configuration record
        values.
    all_node_ids : list[int]
        A list of all node identifiers to which messages will be sent.
    current_round : int
        The current round of the federated learning process.
    assignment_function : Callable[[int], list[int] | list[str]]
        A function that assigns client identifiers to a node based on the node
        identifier. It returns a list of client identifiers assigned to the node.
    client_state : dict[str | int, ClientState]
        A dictionary mapping client identifiers to their current state information. This
        information is included in the instructions to provide context to the clients
        about their previous interactions with the server.
    server_steps_cumulative : int
        The cumulative number of training steps performed by the server across all
        rounds. This value is included in the instructions to provide context to the
        clients.
    msg_str : str
        A string prefix used in message creation to identify or categorize the message.

    Yields
    ------
    Generator[Message, None, None]
        A generator that yields the results of the message processing as `Message`
        objects. Each `Message` object represents either a result or an error from the
        processing node.

    Notes
    -----
    The function assumes the existence of a `log` function for logging and a
    `DEFAULT_TTL` constant that defines the time-to-live for messages. It also relies
    on the `Driver` interface for message handling and the `create_merged_recordset`
    function for generating the content of each message.
    """
    log(DEBUG, "Independent messaging.")
    messages = []
    for node_id in all_node_ids:
        cids_to_train = assignment_function(node_id)
        if cids_to_train:
            message = driver.create_message(
                content=create_merged_recordset(
                    sampled_clients=cids_to_train,
                    current_round=current_round,
                    gen_ins_function=gen_ins_function,
                    client_state=client_state,
                    server_steps_cumulative=server_steps_cumulative,
                    msg_str=msg_str,
                ),
                message_type=message_type,
                dst_node_id=node_id,
                group_id=str(current_round),
                ttl=DEFAULT_TTL,
            )
            messages.append(message)
    message_ids = list(driver.push_messages(messages))
    log(DEBUG, "Pushed %s messages: %s", len(messages), message_ids)
    total_messages = len(message_ids)
    received_messages = 0
    while received_messages < total_messages:
        for res in driver.pull_messages(message_ids=message_ids):
            log(DEBUG, f"Got 1 {'result' if res.has_content() else 'error'}")
            received_messages += 1
            yield res


def get_rr_assignment_function(
    sampled_clients: list[int] | list[str],
    all_node_ids: list[int],
) -> Callable[[int], list[int] | list[str]]:
    """Create a round-robin assignment function for distributing clients among nodes.

    Parameters
    ----------
        sampled_clients (list[int] | list[str]): A list of client IDs to be assigned.
        all_node_ids (list[int]): A list of all node IDs available for assignment.

    Returns
    -------
        Callable[[int], list[int] | list[str]]: A function that takes a node ID and
            returns a list of client IDs assigned to that node.
    """

    def assignment_function(node_id: int) -> list[int] | list[str]:
        """Assign clients to the given node ID based on a round-robin distribution.

        Parameters
        ----------
            node_id (int): The ID of the node to assign clients to.

        Returns
        -------
            list[int] | list[str]: A list of client IDs assigned to the node.
        """
        return [
            client_id
            for i, client_id in enumerate(sampled_clients)
            if i % len(all_node_ids) == all_node_ids.index(node_id)
        ]  # type: ignore[reportReturnType,return-value]

    return assignment_function


def create_merged_recordset(
    sampled_clients: list[int] | list[str],
    current_round: int,
    gen_ins_function: Callable[[int, int | str], dict[str, ConfigsRecordValues]],
    client_state: dict[str | int, ClientState],
    server_steps_cumulative: int,
    msg_str: str,
) -> RecordSet:
    """Create a merged record set for the sampled clients in a federated learning round.

    This function generates a `RecordSet` object that contains configuration records for
    each sampled client and a main configuration record that includes the server round
    information. It uses a generator function to create individual client configuration
    records based on the current round and client identifiers. These configurations are
    then merged into a single `RecordSet` object, which also includes an empty `FitIns`
    object with no parameters and an empty configuration, intended for initialization
    purposes.

    Parameters
    ----------
    sampled_clients : list[int] | list[str]
        A list of identifiers for the clients sampled in the current federated learning
        round. These identifiers can be either integers or strings.
    current_round : int
        The current federated learning round number.
    gen_ins_function : Callable[[int, int | str], dict[str, ConfigsRecordValues]]
        A generator function that takes the current round and a client identifier as
        inputs and returns a dictionary representing the client's configuration record
        values.
    client_state : dict[str | int, ClientState]
        A dictionary mapping client identifiers to their current state information. This
        information is included in the instructions to provide context to the clients
        about their previous interactions with the server.
    server_steps_cumulative : int
        The cumulative number of training steps performed by the server across all
        rounds. This value is included in the instructions to provide context to the
        clients.
    msg_str : str
        A string used to prefix the main configuration record key, typically indicating
        the type of message or operation being performed.

    Returns
    -------
    RecordSet
        A `RecordSet` object containing the merged configuration records for all sampled
        clients and the main configuration record with the server round information.

    Notes
    -----
    The `RecordSet` object is a custom data structure used to aggregate and manage
    different types of records,such as configurations and inputs for federated
    learning operations. The `ConfigsRecord` and `FitIns` are also custom data
    structures representing configuration records and federated learning instructions,
    respectively.
    """
    # Create shared recordset for all clients in this assignment
    record_set = fit_or_evaluate_ins_recordset(
        msg_str, current_round, sampled_clients, client_state, server_steps_cumulative
    )
    # Create a config record for each client
    configs = {
        str(cid): ConfigsRecord(gen_ins_function(current_round, cid))
        for cid in sampled_clients
    }
    # Add the client config records to the main record set
    record_set.configs_records.update(configs)
    return record_set


def fit_or_evaluate_ins_recordset(
    msg_str: str,
    current_round: int,
    sampled_clients: list[int] | list[str],
    client_state: dict[str | int, ClientState],
    server_steps_cumulative: int,
) -> RecordSet:
    """Create a RecordSet for fit or evaluation instructions based on the message type.

    This function generates a RecordSet for either fitting or evaluation instructions,
    depending on thecmessage string provided (`msg_str`). It supports creating
    instructions for a list of sampled clients, incorporating the current server round
    and client IDs into the configuration of the instructions. The function is designed
    to work with federated learning scenarios where instructions need to be dynamically
    generated and dispatched to clients based on the current round of training or
    evaluation.

    Parameters
    ----------
    msg_str : str
        A string indicating the type of instructions to generate. Expected values are
        "fitins" for fitting instructions or "evaluateins" for evaluation instructions.
    current_round : int
        The current round of the federated learning process. This is used to track the
        progress of the learning or evaluation over time.
    sampled_clients : list[int] | list[str]
        A list of client identifiers (either integers or strings) that have been sampled
        for participation in the current round. These identifiers are included in the
        instructions to specify the target clients.
    client_state : dict[str | int, ClientState]
        A dictionary mapping client identifiers to their current state information. This
        information is included in the instructions to provide context to the clients
        about their previous interactions with the server.
    server_steps_cumulative : int
        The cumulative number of training steps performed by the server across all
        rounds. This value is included in the instructions to provide context to the
        clients.

    Returns
    -------
    RecordSet
        A RecordSet object containing the generated instructions for fitting or
        evaluation. The RecordSet includes parameters and configuration tailored to the
        specified clients and the current round.

    Raises
    ------
    AssertionError
        If the function fails to create a RecordSet, indicating an issue with the input
        parameters or the generation process.

    Notes
    -----
    - The function uses `fitins_to_recordset` and `evaluateins_to_recordset` to convert
        fitting or evaluation instructions into a RecordSet format suitable for
        transmission to clients.
    - The `parameters` field of the instructions is initialized with an empty tensor,
        indicating that no initial parameters are provided to the clients.
    - The configuration includes the `server_round` to inform clients of the current
        round and `client_ids` to specify the target clients for these instructions.
    - This function is part of a federated learning server utility and assumes the
        existence of `FitIns`, `EvaluateIns`, `Parameters`, `RecordSet`,
        `fitins_to_recordset`, and `evaluateins_to_recordset` classes or functions.
    """
    recordset: RecordSet | None = None
    match msg_str:
        case "fitins":
            # Create shared recordset for all clients in this assignment
            recordset = fitins_to_recordset(
                FitIns(
                    parameters=Parameters(tensors=[], tensor_type="empty"),
                    # NOTE: We always need to pass the server round to the config record
                    # TODO: With Pollen, client ids are assigned to specific GPUs
                    config={
                        "server_round": current_round,
                        "client_ids": str(sampled_clients),
                        "client_state": str(
                            {k: asdict(v) for k, v in client_state.items()}
                        ),
                        "server_steps_cumulative": server_steps_cumulative,
                    },
                ),
                keep_input=True,
            )
        case "evaluateins":
            # Create shared recordset for all clients in this assignment
            recordset = evaluateins_to_recordset(
                EvaluateIns(
                    parameters=Parameters(tensors=[], tensor_type="empty"),
                    # NOTE: We always need to pass the server round to the config record
                    # TODO: With Pollen, client ids are assigned to specific GPUs
                    config={
                        "server_round": current_round,
                        "client_ids": str(sampled_clients),
                        "client_state": str(
                            {k: asdict(v) for k, v in client_state.items()}
                        ),
                        "server_steps_cumulative": server_steps_cumulative,
                    },
                ),
                keep_input=True,
            )
    assert recordset is not None, "Recordset must be created"
    return recordset
