---
name: "google_speech"
data_root: "/datasets/FedScale/google_speech/google_speech"
learning_rate: 0.05
num_rounds: 100
n_clients_per_round: 100
batch_size: 20
momentum: 0.9
weight_decay: 5e-4
strategy:
  _target_: rs_fedyogi.FedYogiRSModel
  eta: 3e-3 
  tau: 1e-8
  beta_1: 0.9
  beta_2: 0.99
is_fake: False
n_clients: -1