#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!
#SBATCH --nodelist=mauao,ngongotaha
#SBATCH --gres=gpu:1
#SBATCH --job-name=pollen_worker_multinode
#SBATCH --cpus-per-task 8
### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --ntasks-per-node=1

#! Need to force the nodes. Otherwise, the nodes might be allocated randomly.
#! Head node is `mauao`, 128.232.115.0
node_1="mauao"
node_2="ngongotaha"
ip="128.232.115.0"

# Get the timestamp and the unique run id
timestamp=$(date +%Y-%m-%d_%H%M%S)
run_uuid=$(uuidgen)
# activate the environment and go to the pollen_worker directory
source /nfs-share/ls985/anaconda3/bin/activate ray111-test
cd /nfs-share/ls985/pollen_worker

# Set the custom hydra arguments that will be passed to the server and the node manager
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=shakespeare_memory task.n_clients_per_round=200 task.num_rounds=100 local_epochs=1 placement_policy=lb flwr_address=$ip:6379"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=shakespeare_memory task.n_clients_per_round=200 task.num_rounds=100 local_epochs=1 placement_policy=llb flwr_address=$ip:6380"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=shakespeare_memory task.n_clients_per_round=200 task.num_rounds=100 local_epochs=1 placement_policy=rr flwr_address=$ip:6381"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=openimage task.n_clients_per_round=100 task.num_rounds=100 local_epochs=1 placement_policy=lb flwr_address=$ip:6382"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=openimage task.n_clients_per_round=100 task.num_rounds=100 local_epochs=1 placement_policy=llb flwr_address=$ip:6383"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=openimage task.n_clients_per_round=100 task.num_rounds=100 local_epochs=1 placement_policy=rr flwr_address=$ip:6384"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=google_speech task.n_clients_per_round=100 task.num_rounds=100 local_epochs=1 placement_policy=lb flwr_address=$ip:6385"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=google_speech task.n_clients_per_round=100 task.num_rounds=100 local_epochs=1 placement_policy=llb flwr_address=$ip:6386"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=google_speech task.n_clients_per_round=100 task.num_rounds=100 local_epochs=1 placement_policy=rr flwr_address=$ip:6387"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=reddit task.n_clients_per_round=100 task.num_rounds=100 local_epochs=1 placement_policy=lb flwr_address=$ip:6388"
CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=reddit task.n_clients_per_round=100 task.num_rounds=100 local_epochs=1 placement_policy=llb flwr_address=$ip:6389"
# CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=reddit task.n_clients_per_round=100 task.num_rounds=100 local_epochs=1 placement_policy=rr flwr_address=$ip:6390"

echo "STARTING POLLEN SERVER at $node_1"
python server_with+pollen.py $CUSTOM_HYDRA_ARGS &

echo "STARTING POLLEN NODE MANAGER at $node_1"
srun --nodes=1 --ntasks=1 -w "$node_1" \
    python pure_sh_node_manager.py $CUSTOM_HYDRA_ARGS &

echo "STARTING POLLEN NODE MANAGER at $node_2"
srun --nodes=1 --ntasks=1 -w "$node_2" \
    python pure_sh_node_manager.py $CUSTOM_HYDRA_ARGS


# How to use this script? Use what follows for a interactive job
# srun --nodelist mauao,ngongotaha --cpus-per-task 8 --ntasks-per-node=1 --gres=gpu:1 --partition=interactive bash slurm_pollen_multinode.sh
# Use what follows for a batch job
# sbatch slurm_pollen_multinode.sh