---
local_epochs: 1
flwr_address: "127.0.0.1:1042"
ray_address: "localhost:8042"
run_uuid: 0

# Task
defaults:
  - _self_
  - task: "shakespeare_memory"

gen_num_total_virtual_clients:
  _target_: utils.shakespeare_gen_num_total_virtual_clients
  data_root: ${task.data_root}
  dataset: "train"
  min_samples_per_client: ${task.batch_size}

# Client Fit Function
gen_client_fn:
  _target_: virtual_client.gen_client_fn
  name: ${task.name}

gen_on_fit_config_fn:
  _target_: utils.gen_on_fit_config_fn
  batch_size: ${task.batch_size}
  local_epochs: ${local_epochs}
  learning_rate: ${task.learning_rate}
  momentum: ${task.momentum}
  weight_decay: ${task.weight_decay}
