---
dataset_name: "shakespeare"
data_root: "/datasets/FedScale/shakespeare/"
num_classes: 10
batch_size: 20
num_local_epochs_per_round: 2
num_total_clients: 500
num_rounds: 4000
weight_decay: 5e-4
momentum: 0.9
learning_rate: 0.8

# Aggregation Strategy
fraction_fit: 0.037

gen_num_total_virtual_clients:
  _target_: utils.shakespeare_gen_num_total_virtual_clients
  data_root: ${data_root}
  dataset: "train"
  min_samples_per_client: 20

# Client Fit Function
gen_client_fit_fn:
  _target_: utils.shakespeare_gen_client_fit_fn
  data_root: ${data_root}
  batch_size: ${batch_size}
  num_local_epochs_per_round: ${num_local_epochs_per_round}
  learning_rate: ${learning_rate}
  momentum: ${momentum}
  weight_decay: ${weight_decay}