---
batch_size: 4
dataset_name: "shakespeare"
data_root: "/datasets/FedScale/leaf_shakespeare"
learning_rate: 0.8
local_epochs: 1
momentum: 0.9
num_classes: 10
num_rounds: 100
weight_decay: 5e-4

# Aggregation Strategy
fraction_fit: 0.037

gen_num_total_virtual_clients:
  _target_: utils.shakespeare_gen_num_total_virtual_clients
  data_root: ${data_root}
  dataset: "train"
  min_samples_per_client: 20

# Client Fit Function
gen_client_fn:
  _target_: clients.gen_shakespeare_client_fn
  data_root: ${data_root}

gen_on_fit_config_fn:
  _target_: utils.gen_on_fit_config_fn
  batch_size: ${batch_size}
  local_epochs: ${local_epochs}
  learning_rate: ${learning_rate}
  momentum: ${momentum}
  weight_decay: ${weight_decay}