---
run_uuid: chiappe
seed: 1337
is_test: false

# Pollen specific settings
pollen:
  placement_policy: rr # "rr", "srr", "bu", "su", "lbu", "lb", "llb"
  n_nodes: 1
  server_address: localhost:50734
  saving_path: /tmp/pollen

fl:
  n_total_clients: 8
  n_clients_per_round: 8
  n_rounds: 200

# Defaults
defaults:
  - _self_
  - llm_config: mpt-125m

# TODO: FL specific training instructions 
# gen_on_fit_config_fn:
#   _target_: pollen_worker.utils.gen_on_fit_config_fn
#   batch_size: ${task.batch_size}
#   local_epochs: ${local_epochs}
#   learning_rate: ${task.learning_rate}
#   momentum: ${task.momentum}
#   weight_decay: ${task.weight_decay}
#   is_fake: ${task.is_fake}
#   n_workers: ${task.n_workers}

# Weights&Biases
use_wandb: true

wandb:
  setup:
    project: pollen-llm
    group: llm
    tags:
      - run_uuid_${run_uuid}
      # - learning_rate_${task.learning_rate}
      # - local_epochs_${local_epochs}
      # - batch_size_${task.batch_size}
    entity: null
    mode: online
  start_eval: 0
