---
local_epochs: 1
flwr_address: 127.0.0.1:1042
ray_address: localhost:8042
ray_redis_password: culo
ray_node_ip_address: localhost
run_uuid: 0
save_freq: 100
output_dir: /nfs-share/ls985/pollen_worker/outputs/2023-09-01/16-20-25
multirun_output_dir: null
seed: 1337
placement_policy: rr # "rr", "srr", "bu", "su", "lbu", "lb", "llb""
num_nodes: 1

# Task
defaults:
  - _self_
  - task: reddit

gen_num_total_virtual_clients:
  _target_: pollen_worker.utils.shakespeare_gen_num_total_virtual_clients
  data_root: ${task.data_root}
  dataset: train
  min_samples_per_client: ${task.batch_size}

# Client Fit Function
gen_client_fn:
  _target_: pollen_worker.virtual_client.gen_client_fn
  name: ${task.name}

gen_on_fit_config_fn:
  _target_: pollen_worker.utils.gen_on_fit_config_fn
  batch_size: ${task.batch_size}
  local_epochs: ${local_epochs}
  learning_rate: ${task.learning_rate}
  momentum: ${task.momentum}
  weight_decay: ${task.weight_decay}
  is_fake: ${task.is_fake}

use_wandb: false

wandb:
  setup:
    project: pollen
    group: ${task.data_root}
    tags:
      - run_uuid_${run_uuid}
      - learning_rate_${task.learning_rate}
      - local_epochs_${local_epochs}
      - batch_size_${task.batch_size}
    entity: null
    mode: online
  start_eval: 0
