---
# General parameters
local_epochs: 1
flwr_address: null
ray_address: null
ray_redis_password: null
ray_node_ip_address: null
run_uuid: null
save_freq: 100
output_dir: null
multirun_output_dir: null
seed: 1337
placement_policy: lb # "rr", "srr", "bu", "su", "lbu", "lb", "llb""
num_nodes: 1
cap_num_workers_per_gpu: null
concurrency_estimator: false

# Task
defaults:
  - _self_
  - task: shakespeare_memory

# Client Fit Function
gen_client_fn:
  _target_: pollen_worker.virtual_client.gen_client_fn
  name: ${task.name}

# Fit configuration
gen_on_fit_config_fn:
  _target_: pollen_worker.utils.gen_on_fit_config_fn
  batch_size: ${task.batch_size}
  local_epochs: ${local_epochs}
  learning_rate: ${task.learning_rate}
  momentum: ${task.momentum}
  weight_decay: ${task.weight_decay}
  is_fake: ${task.is_fake}
  n_workers: ${task.n_workers}

# Wandb configuration
use_wandb: false

wandb:
  setup:
    project: pollen
    group: ${task.data_root}
    id: ${run_uuid}
    tags:
      - run_uuid_${run_uuid}
      - learning_rate_${task.learning_rate}
      - local_epochs_${local_epochs}
      - batch_size_${task.batch_size}
    entity: null
    mode: online
  start_eval: 0
