#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!
#SBATCH --job-name=ray_multinode
### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodelist=ngongotaha,mauao
### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100G

# Load modules or your own conda environment here
cd /nfs-share/ls985/pollen_worker
poetry shell

# ===== DO NOT CHANGE THINGS HERE UNLESS YOU KNOW WHAT YOU ARE DOING =====
# This script is a modification to the implementation suggest by gregSchwartz18 here:
# https://github.com/ray-project/ray/issues/826#issuecomment-522116599
redis_password=$(uuidgen)
export redis_password

main_port=8379
port1=8700
port2=8701
port3=10001
port4=8702
port5=10002
port6=19999
ip="128.232.115.66"
ip_head=$ip:$main_port
export ip_head
echo "IP Head: $ip_head"

export NUM_GPUS=`echo $CUDA_VISIBLE_DEVICES | awk 'BEGIN{FS=","};{print NF}'`
echo "NUM_GPUS: $NUM_GPUS"
echo "SLURM_CPUS_PER_TASK: $SLURM_CPUS_PER_TASK"

#! NOTE: Forcing the head node to be ngongotaha, otherwise it crashes
node_1="ngongotaha"
echo "STARTING HEAD at $node_1"
srun --nodes=1 --ntasks=1 -w "$node_1" \
  poetry run ray start --head --node-ip-address=$ip --num-gpus=${NUM_GPUS} --num-cpus=${SLURM_CPUS_PER_TASK} \
      --port=$main_port \
      --node-manager-port=$port1 \
      --object-manager-port=$port2 \
      --ray-client-server-port=$port3 \
      --redis-shard-ports=$port4 \
      --min-worker-port=$port5 \
      --max-worker-port=$port6 \
      --redis-password="$redis_password" \
      --verbose \
      --include-dashboard=False \
      --block &

sleep 30

node_2="mauao"
echo "STARTING WORKER $i at $node_2"
srun --nodes=1 --ntasks=1 -w "$node_2" \
  poetry run ray start --address "$ip_head" --redis-password="$redis_password" --num-gpus=1 --num-cpus=${SLURM_CPUS_PER_TASK} --block &

sleep 5

this_hostname=$(hostname)

# ===== Call your code below =====
# Set the custom hydra arguments that will be passed to the server and the node manager
CUSTOM_HYDRA_ARGS="num_nodes=2 run_uuid=$run_uuid task=shakespeare_memory task.n_clients_per_round=10 task.num_rounds=2 local_epochs=1 ray_address=auto ray_redis_password=$redis_password ray_node_ip_address=$ip"

echo "LAUNCHING SIMULATION at this_hostname"
# srun --nodes=1 --ntasks=1 -w "$node_1" \
poetry run python pollen_worker/ray_simulation.py $CUSTOM_HYDRA_ARGS 

# How to use this script? Use what follows for a interactive job
# srun --nodelist mauao,ngongotaha --cpus-per-task 8 --ntasks-per-node=1 --gres=gpu:1 --partition=interactive bash lorenzo_slurm/slurm_ray_multinode.sh
# Use what follows for a batch job
# sbatch lorenzo_slurm/slurm_ray_multinode.sh
