#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!
#SBATCH --job-name=pollen_worker_multinode
### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodelist=ngongotaha,mauao
### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8

# Load modules or your own conda environment here
# module load pytorch/v1.4.0-gpu
# conda activate ${CONDA_ENV}
cd /nfs-share/ls985/pollen_worker
poetry shell

# ===== DO NOT CHANGE THINGS HERE UNLESS YOU KNOW WHAT YOU ARE DOING =====
# This script is a modification to the implementation suggest by gregSchwartz18 here:
# https://github.com/ray-project/ray/issues/826#issuecomment-522116599
redis_password=$(uuidgen)
export redis_password

nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST") # Getting the node names
nodes_array=($nodes)

node_1=${nodes_array[0]}
ip=$(srun --nodes=1 --ntasks=1 -w "$node_1" hostname --ip-address) # making redis-address

# if we detect a space character in the head node IP, we'll
# convert it to an ipv4 address. This step is optional.
if [[ "$ip" == *" "* ]]; then
  IFS=' ' read -ra ADDR <<< "$ip"
  if [[ ${#ADDR[0]} -gt 16 ]]; then
    ip=${ADDR[1]}
  else
    ip=${ADDR[0]}
  fi
  echo "IPV6 address detected. We split the IPV4 address as $ip"
fi

port=6379
ip="128.232.115.66"
ip_head=$ip:$port
export ip_head
echo "IP Head: $ip_head"

node_1="ngongotaha"
echo "STARTING HEAD at $node_1"
srun --nodes=1 --ntasks=1 -w "$node_1" \
  ray start --head --node-ip-address="$ip" --port=$port --redis-password="$redis_password" --disable-usage-stats --block &
  # ray start --head --node-ip-address="128.232.115.0" --port=6379 --redis-password="culo" --disable-usage-stats --block &
  # ray start --head --node-ip-address="128.232.115.66" --port=6379 --redis-password="culo" --disable-usage-stats --block &
sleep 30

worker_num=$((SLURM_JOB_NUM_NODES - 1)) #number of nodes other than the head node
for ((i = 1; i <= worker_num; i++)); do
  node_i=${nodes_array[$i]}
  node_i="mauao"
  echo "STARTING WORKER $i at $node_i"
  srun --nodes=1 --ntasks=1 -w "$node_i" \
    ray start --address "$ip_head" --redis-password="$redis_password" --block &
    # ray start --address "128.232.115.0:6379" --redis-password="culo" --block &
    # ray start --address "128.232.115.66:6379" --redis-password="culo" --block &
  sleep 5
done

# ===== Call your code below =====
# Set the custom hydra arguments that will be passed to the server and the node manager
# CUSTOM_HYDRA_ARGS="run_uuid=$(uuidgen) task=shakespeare_memory task.n_clients_per_round=200 task.num_rounds=100 local_epochs=1 ray_address=auto is_multinode=True"
CUSTOM_HYDRA_ARGS="run_uuid=$(uuidgen) task=openimage task.n_clients_per_round=200 task.num_rounds=100 local_epochs=1 ray_address=auto is_multinode=True"

echo "LAUNCHING SIMULATION"
poetry run python pollen_worker/ray_simulation.py $CUSTOM_HYDRA_ARGS 

# How to use this script? Use what follows for a interactive job
# srun --nodelist mauao,ngongotaha --cpus-per-task 8 --ntasks-per-node=1 --gres=gpu:1 --partition=interactive bash lorenzo_slurm/slurm_ray_multinode.sh
# Use what follows for a batch job
# sbatch lorenzo_slurm/slurm_ray_multinode.sh