---
name: flair
data_root: /datasets/flair
learning_rate: 0.01
num_rounds: 100
n_clients_per_round: 200
batch_size: 16
momentum: .0
weight_decay: .0
n_workers: 0

strategy:
  _target_: pollen_worker.rs_fedavg.FedAvgRSModel

is_fake: false
n_clients: -1
